// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydrlcunmhcgmbxpsztbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkcmxjdW5taGNnbWJ4cHN6dGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTU2MDEsImV4cCI6MjA2NzkzMTYwMX0.WxpU5jvueJz3ano89oSJxBGwhtPEfx3j6UaQv_3wT3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});